# Generated by Django 3.2.7 on 2022-05-15 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20211010_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='got_it_right',
            field=models.BooleanField(default=0, verbose_name='acertou'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='public',
            field=models.BooleanField(default=0, verbose_name='Publica'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attempt',
            name='difficult',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Difficult')], verbose_name='Dificuldade'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question', verbose_name='Questão'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuários'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=500, verbose_name='Resposta'),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Questão'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.TextField(null=True, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='question',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.theme', verbose_name='Tema'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuários'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Tema'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=60, verbose_name='Categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.AddField(
            model_name='theme',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='Categoria'),
        ),
    ]
